spring:
  application:
    name: brewery-order-service
  datasource:
    url: jdbc:h2:mem:brewery-order-service;MODE=MYSQL
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  artemis:
    user: artemis-user
    password: artemis-password

queue:
  inventory:
    reserve-stock: beer-inventory-reserve-stock
    release-stock: beer-inventory-release-stock
  notification:
    email: beer-notification-send-email
    sms: beer-notification-send-sms
  order:
    validate: beer-order-validate
    allocate: beer-order-allocate
    allocate-failure: beer-order-allocate-failure
    deallocate: beer-order-deallocate

http-client:
  max-total: 50
  max-per-route: 20
  socket-timeout: PT5S
  idle-timeout: PT60S
  keep-alive-time: PT5S

rest:
  inventory:
    service: "http://localhost:8081/api/v1/inventories/"
server:
  port: 8082
