package pl.excellentapp.brewery.order.domain.order;

public enum BeerOrderEvent {

    VALIDATE_ORDER, VALIDATION_PASSED, VALIDATION_FAILED,
    ALLOCATE_ORDER, ALLOCATION_SUCCESS, ALLOCATION_NO_INVENTORY, ALLOCATION_FAILED,
    BEER_ORDER_PICKED_UP, CANCEL_BY_USER, CANCEL_BY_SYSTEM,
}
