package pl.excellentapp.brewery.order.domain.order;

public enum BeerOrderStatus {

    NEW, VALIDATED, VALIDATION_PENDING, VALIDATION_EXCEPTION,
    ALLOCATION_PENDING, ALLOCATED, ALLOCATION_EXCEPTION, CANCELLED_BY_USER, CANCELLED_BY_SYSTEM,
    PENDING_INVENTORY, PICKED_UP, DELIVERED, DELIVERY_EXCEPTION

}
